line_notify:
  channel_access_token: lFpN63Hog/WYBq9iU9xJV036WSDtN3pdv9pTG3JoGjoD09jlWI//y01sWaZ4VS+j6IR0y7myzwssciMlM0mHWOJnNLM5f2fTAIF1ykxgtNz75Hd25tMSrh9rhIRV3/m1mnbxyjR1UYX2gv3cOmQsVgdB04t89/1O/w1cDnyilFU=
  user_id: U3fac860e1000bf3982f6c89cac18eb91
monitor:
  interval_seconds: 300
  jitter_min_seconds: 5
  jitter_max_seconds: 15
  request_timeout: 10
  state_file: state.json
  notify_on_initial_stock: true
  heartbeat_time: 09:00
targets:
- name: 副廠變壓器 適用型號 UX370 UX390 UX390UA UX370UA Q325,Q325UA T303UA T305CA T302CA ADP-45GW
    ADP-45EW A ADP-45EW B Latitude 11 5175 5179 12 7275 9250 TPN-CA01 TPN-CA02 副廠變壓器
  url: https://24h.pchome.com.tw/prod/QAAH2V-A90099QVY
  max_price: 605
  enabled: true
- name: 高品質變壓器 UX305FA UX305F UX305 S200e X102b Taichi 21 Zenbook Prime BX21A BX31A
    BX32A UX21a Zenbook UX21A UX31A UX31LA Transformer Book Trio Tx201 Tx201la Gigabyte
    X11
  url: https://24h.pchome.com.tw/prod/DCABJR-A9006KAYJ
  max_price: 605
  enabled: true
- name: BEYBLADE X 戰鬥陀螺 UX-11 衝擊龍神 豪華組 (台版) + Amiibo 卡比&傳送之星 卡比的馭天飛行
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900KBB3K
  max_price: 605
  enabled: true
- name: 四方型 19V 3.42A 65W 變壓器  TX201 S510U S410U A553M K556UQ K556U X540M X540S X453
    E402N UX305F UX305FA BX32A UX410UQ X542 X542U X556 X556U X556UB S410UN UX303L
    X556變壓器  ux305f 充電器  19v 3.42a
  url: https://24h.pchome.com.tw/prod/DCABI3-A900ACDX4
  max_price: 605
  enabled: true
- name: ASUS ux305充電器 w19-045n3c X540S X540M X540SA UX31A UX32A UX305L UX305F UX21A
    UX305F UX305C UX305LA BX32L UX305FA UX305CA X551C UX305F UX360 UX360C UX301 UX303
    UX410UF UX410UQ 19V 2.37A 45W 變壓器 ux410u 充電器  asus充電器 19v 2.37a
  url: https://24h.pchome.com.tw/prod/DCABI3-A900A2J4U
  max_price: 605
  enabled: true
- name: '[UX20]艾瑪1.5尺手提馬鞍椅凳UX20-2501A二色可選-免運費/免組裝/椅凳'
  url: https://24h.pchome.com.tw/prod/DEDDA4-A900C16D3
  max_price: 605
  enabled: true
- name: BEYBLADE X 戰鬥陀螺 UX-20 榮耀武神LF (台版) + NS 巴蘭的異想奇境 中文版 (國際版)
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900KC64Y
  max_price: 605
  enabled: true
- name: BEYBLADE X 戰鬥陀螺 UX-20 榮耀武神LF(台版) + 泡泡瑪特 THE MONSTERS 春天野在家系列
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900KBB42
  max_price: 605
  enabled: true
- name: UX-20 榮耀女武神
  url: https://24h.pchome.com.tw/prod/DEASSW-A900KBFXP
  max_price: 605
  enabled: true
- name: Takara Tomy Beyblade 戰鬥陀螺 X 世代 UX-20 榮耀女武神 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K7SN6
  max_price: 605
  enabled: true
- name: 充電器 電源線 GF75 Thin MS-17F5 ASUS 華碩 F571 F571GD K571 K571GT X571 X571G G501
    G501J N501 N501JW UX501 UX501JW UX550 UX550GE UX580 UX580GD UX580GE UX561U UP6502
  url: https://24h.pchome.com.tw/prod/DCABI1-A900FKAN0
  max_price: 605
  enabled: true
- name: 150W 充電器(保固更久) 適用  20V,7.5A (相容19.5V,7.7A) UX580,UX550,UX561,UX580G,UX561U,UX550GE,UX550VD,UX550VE,UX580GE,ADP-150CH
    B,A17-150P1A,X571G,X571GT,NX550JK,FX570,FX570UD
  url: https://24h.pchome.com.tw/prod/QAAH36-A900ADTSA
  max_price: 605
  enabled: true
- name: 20V, 7.5A,150W 充電器(保固更久) 適用  19.5V,7.7A,150W,UX580G,UX561U,UX550GE,UX550VD,UX550VE,UX580GE,UX561U,UX561UD,UX561UN,FX570,FX570UD,FX86F,Q535,Q535U,Q535UD,X571,X571G,X571GT,NX550JK,ADP-150CH
    B,A17-150P1A,
  url: https://24h.pchome.com.tw/prod/DCABIC-A900ADH9V
  max_price: 605
  enabled: true
- name: UX-17 隕星龍騎士
  url: https://24h.pchome.com.tw/prod/DEASSW-A900KBFYF
  max_price: 605
  enabled: true
- name: BEYBLADE X 戰鬥陀螺 BX-35 隨機強化組Vol.04 (台版) + PS5 改裝機甲大戰 中文版
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900KCFGH
  max_price: 439
  enabled: true
- name: TAKARATOMY BEYBLADE X 戰鬥陀螺X BX-35 隨機強貨組 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5JPP
  max_price: 439
  enabled: true
- name: BEYBLADE X 戰鬥陀螺 BX-35 隨機強化組Vol.04 (台版) + PS5 悟空 傳奇版
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K9IHO
  max_price: 439
  enabled: true
- name: BEYBLADE X 戰鬥陀螺 BX-35 隨機強化組Vol.04 (台版) + PS5 心靈之眼 中文版
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K9IHK
  max_price: 439
  enabled: true
- name: BEYBLADE X 戰鬥陀螺 BX-35 隨機強化組Vol.04 (台版) + PS5 高譚騎士 中文版 (國際版)
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K9IGZ
  max_price: 439
  enabled: true
- name: Funbox 官方限定商品
  url: https://shop.funbox.com.tw/products/tm07984
  max_price: 439
  enabled: true
- name: BX-25 戰鬥陀螺X專業收納包
  url: https://24h.pchome.com.tw/prod/DEASR1-B900H2BID
  max_price: 1319
  enabled: true
- name: BX-37 雙重極限衝擊戰鬥盤豪華組
  url: https://www.toysrus.com.tw/zh-tw/beyblade-bx-37-dual-extreme-impact-combat-disk-deluxe-edition-10058492.html
  max_price: 1648
  enabled: true
- name: Momo 戰鬥陀螺X專區商品
  url: https://www.momoshop.com.tw/goods/GoodsDetail.jsp?i_code=12953255
  max_price: 439
  enabled: true
- name: 蝦皮 Funbox 官方旗艦店熱門款
  url: https://shopee.tw/product/42721867/25578850687
  max_price: 439
  enabled: true
- name: 酷比樂戰鬥陀螺X商品
  url: https://preorder.amuzinc.com/
  max_price: 439
  enabled: false
- name: 誠品線上玩具專區
  url: https://www.eslite.com/
  max_price: 439
  enabled: false
- name: 戰鬥陀螺 CX-18-1紫綠色 籤王 腕龍鞭打 Nr軸 確定版強化組 BB09617 BEYBLADE X
  url: https://24h.pchome.com.tw/prod/DEASR1-B900KCPVW
  max_price: 715
  enabled: true
- name: 日本 戰鬥陀螺 BXG-04 銀牙烈虎S  BEYBLADE X
  url: https://24h.pchome.com.tw/prod/DEASR1-B900HGAF2
  max_price: 825
  enabled: true
- name: 戰鬥陀螺 BX00 暴風天馬3 7-70RA 右旋 BXG-47 BEYBLADE X
  url: https://24h.pchome.com.tw/prod/DEASR1-B900K8AQY
  max_price: 1099
  enabled: true
- name: 日本戰鬥陀螺 BXG-01 烈焰飛鳳SBB91050 BEYBLADE X公司貨 TAKARA TOMY
  url: https://24h.pchome.com.tw/prod/DEASR1-B900GK0S2
  max_price: 825
  enabled: true
- name: Beyblade X 戰鬥陀螺X BX-05 魔導幻箭 魔法箭 巫師之箭 4-80O 組裝強化包 (美版)
  url: https://24h.pchome.com.tw/prod/DEASSW-A900K80FB
  max_price: 439
  enabled: true
- name: 戰鬥陀螺 CX-18-2 金色 腕龍鞭打 Nr軸 確定版強化組 BB09617 BEYBLADE X
  url: https://24h.pchome.com.tw/prod/DEASR1-B900KCPWV
  max_price: 715
  enabled: true
- name: 日版空運 戰鬥陀螺 BX-40 左迴旋 發射器(酒紅) BEYBLADE X
  url: https://24h.pchome.com.tw/prod/DEASR1-B900K4JVW
  max_price: 275
  enabled: true
- name: Beyblade X   隕星龍騎士 UX-17 系列 美版3-70J 附拉繩發射器
  url: https://24h.pchome.com.tw/prod/DEASSW-A900KCF5L
  max_price: 605
  enabled: true
- name: 戰鬥陀螺 UX-19 子彈獅鷲 H 台灣版 麗嬰代理 附 QRCODE BEYBLADE X
  url: https://24h.pchome.com.tw/prod/DEASR1-B900K7V73
  max_price: 605
  enabled: true
- name: 戰鬥陀螺 BEYBLADE BURST#44 B-44 聖光神鷹
  url: https://24h.pchome.com.tw/prod/QFAS11-A9008Z134
  max_price: 439
  enabled: true
- name: 戰鬥陀螺 UX-21 惡魔幽冥改造組 BEYBLADE X 台版附QRCODE
  url: https://24h.pchome.com.tw/prod/DEASR1-B900KD01F
  max_price: 1539
  enabled: true
- name: 戰鬥陀螺 UX-20 榮耀武神LF 右旋 BEYBLADE X 台灣版 麗嬰代理
  url: https://24h.pchome.com.tw/prod/DEASR1-B900K8AYJ
  max_price: 605
  enabled: true
- name: 戰鬥陀螺 CX-18-3 黑色 腕龍鞭打 Nr軸 確定版強化組 BB09617 BEYBLADE X
  url: https://24h.pchome.com.tw/prod/DEASR1-B900KCPXK
  max_price: 715
  enabled: true
- name: Beyblade X 戰鬥陀螺 X UX-01 蒼龍爆刃 BURSER DRAN-60A 美版
  url: https://24h.pchome.com.tw/prod/DEASSW-A900K7UYN
  max_price: 605
  enabled: true
- name: 戰鬥陀螺 BX-18 X旋風發射器 BEYBLADE X TAKARA TOMY BB91305
  url: https://24h.pchome.com.tw/prod/DEASR1-B900GRH36
  max_price: 275
  enabled: true
- name: 日本戰鬥陀螺 BX-26獨角刺心 BB91446 BEYBLADE X
  url: https://24h.pchome.com.tw/prod/DEASR1-B900H4Q1P
  max_price: 439
  enabled: true
- name: 戰鬥陀螺 BX-51 旋風發射器 黑綠 右旋 BB08926 BEYBLADE X 麗嬰代理
  url: https://24h.pchome.com.tw/prod/DEASR1-B900K4D29
  max_price: 275
  enabled: true
- name: 戰鬥陀螺 BX-00 蒼龍神劍 V2 3-60F 攻擊型 BEYBLADE X 台版附QRCODE
  url: https://24h.pchome.com.tw/prod/DEASR1-B900KD024
  max_price: 439
  enabled: true
- name: Beyblade X 戰鬥陀螺X BX-23  鳳凰飛翼 9-60GF 含一組豪華發射器 (美版)
  url: https://24h.pchome.com.tw/prod/DEASSW-A900KA4E6
  max_price: 439
  enabled: true
- name: 戰鬥陀螺X BX-50 天堂日輪 0-80DS 隨機強化包Vol.11 BX-50
  url: https://24h.pchome.com.tw/prod/DXAX9O-A900KDFKP
  max_price: 439
  enabled: true
- name: TAKARA TOMY BEYBLADE X 戰鬥陀螺X BX-10 極限衝擊戰鬥盤 戰鬥陀螺配件 陀螺 四方型鬥盤
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5JOU
  max_price: 825
  enabled: true
- name: Takara Tomy Beyblade X 戰鬥陀螺 X 世代 BX-32 寬型極限衝擊戰鬥盤 戰鬥陀螺配件
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K26IN
  max_price: 989
  enabled: true
- name: Takara Tomy Beyblade X 戰鬥陀螺 戰鬥陀螺 X 專業收納包 BX-25 黑色 齒輪箱 正版
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K1F6M
  max_price: 1319
  enabled: true
- name: Beyblade 戰鬥陀螺 X世代 BX-27 幻神護甲 隨機強化組 (韓版)
  url: https://24h.pchome.com.tw/prod/DGBJQR-A900K3IL5
  max_price: 439
  enabled: true
- name: Beyblade 戰鬥陀螺 X世代 BX-31 隨機強化組Vol.3 (韓版)
  url: https://24h.pchome.com.tw/prod/DGBJQR-A900K3CYA
  max_price: 439
  enabled: true
- name: Beyblade 戰鬥陀螺 X世代 BX-24 隨機強化組Vol.2 (韓版)
  url: https://24h.pchome.com.tw/prod/DGBJQR-A900K3CXZ
  max_price: 439
  enabled: true
- name: 戰鬥陀螺 BX-57 3V3 對戰收納盒 黑色版 台版
  url: https://24h.pchome.com.tw/prod/DEASR1-B900KCSX5
  max_price: 1319
  enabled: true
- name: TAKARATOMY BEYBLADE X 戰鬥陀螺 X 世代 BX-37 雙重極限衝擊戰鬥盤 豪華組 電動盤商品 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5JPR
  max_price: 1648
  enabled: true
- name: Takara Tomy Beyblade X 戰鬥陀螺 BX-46 無限衝擊對戰組 發射器 戰鬥盤 陀螺 (日版)
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K2U4R
  max_price: 1648
  enabled: true
- name: Takara Tomy Beyblade X 戰鬥陀螺 X 世代 BX-15 獅子獵爪 5-60P 爆旋陀螺 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K53CJ
  max_price: 439
  enabled: true
- name: Takara Tomy Beyblade X 戰鬥陀螺 X 世代 BX-04 防禦型陀螺 含發射器 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K53DD
  max_price: 439
  enabled: true
- name: Takara Tomy Beyblade X 戰鬥陀螺 X 專業收納包 BX-43 白色 齒輪箱 正版 陀螺包 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5JPV
  max_price: 1319
  enabled: true
- name: Takara Tomy Beyblade X 戰鬥陀螺 X 世代 BX-21三陀螺套裝 地獄鏈甲組合 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5JOX
  max_price: 439
  enabled: true
- name: Takara Tomy Beyblade X 戰鬥陀螺 X 世代 BX-34 蒼穹龍騎士 附左迴旋發射器 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K53CW
  max_price: 439
  enabled: true
- name: Takara Tomy Beyblade 戰鬥陀螺 X 世代 BX-40 左旋拉繩發射器 黑色 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5JP3
  max_price: 275
  enabled: true
- name: TAKARATOMY BEYBLADE X 戰鬥陀螺X BX-11 發射器握把 不包含發射器 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5JPI
  max_price: 275
  enabled: true
- name: 戰鬥陀螺X UX-20 榮耀女武神 LF 入門套組(含發射器) UX-20
  url: https://24h.pchome.com.tw/prod/DXAX9O-A900KD5IK
  max_price: 605
  enabled: true
- name: Takara Tomy Beyblade X 戰鬥陀螺 X 世代 UX-14 天蠍之茅 070z 組裝強化包 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5SMU
  max_price: 605
  enabled: true
- name: Takara Tomy Beyblade X 戰鬥陀螺 X 世代 UX-13 魔像奇岩1-60UN 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5SMT
  max_price: 605
  enabled: true
- name: Takara Tomy Beyblade X 戰鬥陀螺 X 世代 UX-05 忍者闇影隨機強化組 盲包
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5SMQ
  max_price: 605
  enabled: true
- name: TAKARATOMY BEYBLADE X 戰鬥陀螺X 世代 UX-02 惡魔戰錘 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5SM5
  max_price: 605
  enabled: true
- name: TAKARATOMY BEYBLADE X 戰鬥陀螺X UX-08 霜輝銀狼 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K53CX
  max_price: 605
  enabled: true
- name: TAKARATOMY BEYBLADE X 戰鬥陀螺X UX-16 時鐘幻象隨機強化組 盲包 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5SMB
  max_price: 605
  enabled: true
- name: Takara Tomy Beyblade 戰鬥陀螺 X 世代 UX-19 子彈獅鷲 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5SMY
  max_price: 605
  enabled: true
- name: TAKARATOMY BEYBLADE X 戰鬥陀螺X UX-17 隕星龍騎士 附左迴旋發射器 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5SMV
  max_price: 605
  enabled: true
- name: TAKARATOMY BEYBLADE X 戰鬥陀螺X UX-09 武士星劍豪華組 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5SMS
  max_price: 605
  enabled: true
- name: Takara Tomy Beyblade X 戰鬥陀螺 UX-01 蒼龍爆刃 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5SM3
  max_price: 605
  enabled: true
- name: BEYBLADE X 戰鬥陀螺 UX-11 衝擊龍神 豪華組 (台版) + Amiibo 頭巾瓦豆魯迪&羽翼之星
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900KBB32
  max_price: 605
  enabled: true
- name: BEYBLADE X 戰鬥陀螺 UX-19 子彈獅鷲H (台版) + Q版 魔法世界 玻璃獸 娃娃(隨機款)X1
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900KBB35
  max_price: 605
  enabled: true
- name: TAKARATOMY BEYBLADE X 戰鬥陀螺X 世代 UX-11 衝擊龍神豪華組 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5SM8
  max_price: 605
  enabled: true
- name: TAKARATOMY BEYBLADE X 戰鬥陀螺 X世代 UX-07 鳳凰尾翼改造組 (韓版) 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K5SMR
  max_price: 605
  enabled: true
- name: 玩具反斗城 戰鬥陀螺X商品
  url: https://www.toysrus.com.tw/zh-tw/beyblade%E6%88%B0%E9%AC%A5%E9%99%80%E8%9E%BA-bx-17-%E6%A5%B5%E9%99%90%E8%A1%9D%E6%93%8A%E5%B0%8D%E6%88%B0%E7%B5%84-10008186.html
  max_price: 439
  enabled: true
- name: 玩具反斗城 戰鬥陀螺X商品
  url: https://www.toysrus.com.tw/zh-tw/beyblade%E6%88%B0%E9%AC%A5%E9%99%80%E8%9E%BA-bx-15-%E9%9B%84%E7%8D%85%E7%8D%B5%E7%88%AA-10008185.html
  max_price: 439
  enabled: true
- name: 玩具反斗城 戰鬥陀螺X商品
  url: https://www.toysrus.com.tw/zh-tw/beyblade%E6%88%B0%E9%AC%A5%E9%99%80%E8%9E%BA-bx-16-%E7%8E%8B%E8%9B%87%E9%9E%AD%E5%B0%BE-%E9%9A%A8%E6%A9%9F%E5%BC%B7%E5%8C%96%E7%B5%84-10008187.html
  max_price: 439
  enabled: true
- name: 玩具反斗城 戰鬥陀螺X商品
  url: https://www.toysrus.com.tw/zh-tw/beyblade-b-203-sp-starter-set-1175417.html
  max_price: 439
  enabled: true
- name: 玩具反斗城 戰鬥陀螺X商品
  url: https://www.toysrus.com.tw/zh-tw/beyblade-bx-07-1202166.html
  max_price: 439
  enabled: true
- name: Takara Tomy Beyblade 戰鬥陀螺 X 世代 BX-18 X旋風發射器 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K6GNN
  max_price: 275
  enabled: true
- name: TAKARATOMY BEYBLADE X 戰鬥陀螺X BX-28 旋風發射器 右迴旋(白色) 陀螺
  url: https://24h.pchome.com.tw/prod/DSBE2T-A900K53CZ
  max_price: 275
  enabled: true
